from django.urls import path
from apps.vendors.views import (
    AdminBankAccountDeactivateView,
    AdminBankAccountDetailView,
    AdminBankAccountReviewView,
    AdminBankAccountRestoreView,
    AdminDocumentDeactivateView,
    AdminDocumentDetailView,
    AdminDocumentRestoreView,
    AdminDocumentReviewView,
    AdminSubscriptionPlanDetailView,
    AdminSubscriptionPlanListCreateView,
    AdminVendorBankAccountsView,
    AdminVendorCommissionDetailView,
    AdminVendorCommissionListCreateView,
    AdminVendorDetailView,
    AdminVendorDocumentsView,
    AdminVendorListView,
    AdminVendorRegistrationView,
    AdminVendorStatusUpdateView,
    AdminVendorSubscriptionAssignView,
    AdminVendorSubscriptionsView,
    AdminVendorTeamMemberDeactivateView,
    AdminVendorTeamMemberDetailView,
    AdminVendorTeamMemberRestoreView,
    AdminVendorTeamView,
    VendorBankAccountsSelfView,
    VendorDashboardAttentionView,
    VendorDashboardFleetView,
    VendorDashboardRecentBookingsView,
    VendorDashboardStatsView,
    VendorDashboardStatusView,
    VendorDashboardView,
    VendorDocumentsSelfView,
    VendorProfileView,
    VendorTermsView,
    VendorTermsManageView,
)

urlpatterns = [
    # Vendor's own profile — auth required, no vendor_id in URL.
    path("me/", VendorProfileView.as_view(), name="vendor-profile"),
    # Vendor's own KYC documents — view + submit only, no edit/delete.
    # Vendor-submitted documents always land PENDING for admin review.
    path(
        "me/documents/",
        VendorDocumentsSelfView.as_view(),
        name="vendor-documents-self",
    ),
    # Vendor's own bank accounts — view + submit only, no edit/delete.
    # Vendor-submitted accounts always land PENDING for admin review;
    # they never become the active payout account on their own.
    path(
        "me/bank-accounts/",
        VendorBankAccountsSelfView.as_view(),
        name="vendor-bank-accounts-self",
    ),
    # Vendor's own terms — auth required, no vendor_id in URL.
    path("me/terms/", VendorTermsManageView.as_view(), name="vendor-terms-manage"),
    # Public read of a specific vendor's terms — used by the customer app.
    path("<int:vendor_id>/terms/", VendorTermsView.as_view(), name="vendor-terms"),
    path("me/dashboard/", VendorDashboardView.as_view(), name="vendor-dashboard"),
    path(
        "me/dashboard/status/",
        VendorDashboardStatusView.as_view(),
        name="vendor-dashboard-status",
    ),
    path(
        "me/dashboard/attention/",
        VendorDashboardAttentionView.as_view(),
        name="vendor-dashboard-attention",
    ),
    path(
        "me/dashboard/stats/",
        VendorDashboardStatsView.as_view(),
        name="vendor-dashboard-stats",
    ),
    path(
        "me/dashboard/fleet/",
        VendorDashboardFleetView.as_view(),
        name="vendor-dashboard-fleet",
    ),
    path(
        "me/dashboard/recent-bookings/",
        VendorDashboardRecentBookingsView.as_view(),
        name="vendor-dashboard-recent-bookings",
    ),
    path("admin/vendors/", AdminVendorListView.as_view(), name="admin-vendor-list"),
    path(
        "admin/vendors/<int:vendor_id>/",
        AdminVendorDetailView.as_view(),
        name="admin-vendor-detail",
    ),
    path(
        "admin/vendors/<int:vendor_id>/status/",
        AdminVendorStatusUpdateView.as_view(),
        name="admin-vendor-status",
    ),
    path(
        "admin/vendors/<int:vendor_id>/documents/",
        AdminVendorDocumentsView.as_view(),
        name="admin-vendor-documents",
    ),
    path(
        "admin/documents/<int:doc_id>/review/",
        AdminDocumentReviewView.as_view(),
        name="admin-document-review",
    ),
    path(
        "admin/vendors/<int:vendor_id>/bank-accounts/",
        AdminVendorBankAccountsView.as_view(),
        name="admin-vendor-bank-accounts",
    ),
    path(
        "admin/bank-accounts/<int:account_id>/review/",
        AdminBankAccountReviewView.as_view(),
        name="admin-bank-account-review",
    ),
    path(
        "admin/commissions/",
        AdminVendorCommissionListCreateView.as_view(),
        name="admin-commissions",
    ),
    path(
        "admin/commissions/<int:commission_id>/",
        AdminVendorCommissionDetailView.as_view(),
        name="admin-commission-detail",
    ),
    path(
        "admin/vendors/<int:vendor_id>/subscriptions/",
        AdminVendorSubscriptionsView.as_view(),
        name="admin-vendor-subscriptions",
    ),
    path(
        "admin/vendors/<int:vendor_id>/subscriptions/assign/",
        AdminVendorSubscriptionAssignView.as_view(),
        name="admin-vendor-subscription-assign",
    ),
    path(
        "admin/subscription-plans/",
        AdminSubscriptionPlanListCreateView.as_view(),
        name="admin-subscription-plans",
    ),
    path(
        "admin/subscription-plans/<int:plan_id>/",
        AdminSubscriptionPlanDetailView.as_view(),
        name="admin-subscription-plan-detail",
    ),
    path(
        "admin/register/",
        AdminVendorRegistrationView.as_view(),
        name="admin-vendor-registration",
    ),
    path(
        "admin/vendors/<int:vendor_id>/team/",
        AdminVendorTeamView.as_view(),
        name="admin-vendor-team",
    ),
    path(
        "admin/team/<int:member_id>/",
        AdminVendorTeamMemberDetailView.as_view(),
        name="admin-vendor-team-member-detail",
    ),
    path(
        "admin/team/<int:member_id>/deactivate/",
        AdminVendorTeamMemberDeactivateView.as_view(),
        name="admin-vendor-team-member-deactivate",
    ),
    path(
        "admin/team/<int:member_id>/restore/",
        AdminVendorTeamMemberRestoreView.as_view(),
        name="admin-vendor-team-member-restore",
    ),
    path(
        "admin/documents/<int:doc_id>/",
        AdminDocumentDetailView.as_view(),
        name="admin-document-detail",
    ),
    path(
        "admin/documents/<int:doc_id>/deactivate/",
        AdminDocumentDeactivateView.as_view(),
        name="admin-document-deactivate",
    ),
    path(
        "admin/documents/<int:doc_id>/restore/",
        AdminDocumentRestoreView.as_view(),
        name="admin-document-restore",
    ),
    path(
        "admin/bank-accounts/<int:account_id>/",
        AdminBankAccountDetailView.as_view(),
        name="admin-bank-account-detail",
    ),
    path(
        "admin/bank-accounts/<int:account_id>/deactivate/",
        AdminBankAccountDeactivateView.as_view(),
        name="admin-bank-account-deactivate",
    ),
    path(
        "admin/bank-accounts/<int:account_id>/restore/",
        AdminBankAccountRestoreView.as_view(),
        name="admin-bank-account-restore",
    ),
]
