# Generated by Django 6.0.5 on 2026-06-20 10:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0002_remove_payment_bookings_pa_booking_bf00c8_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('payment_type', models.CharField(choices=[('PARTIAL', 'Partial Payment'), ('FULL', 'Full Payment')], max_length=25)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('gateway', models.CharField(default='CASHFREE', max_length=50)),
                ('gateway_order_id', models.CharField(db_index=True, max_length=200, unique=True)),
                ('gateway_payment_id', models.CharField(blank=True, db_index=True, max_length=200)),
                ('gateway_response', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('INITIATED', 'Initiated'), ('PENDING', 'Pending (Awaiting Gateway)'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded'), ('PARTIALLY_REFUNDED', 'Partially Refunded')], default='INITIATED', max_length=25)),
                ('attempt_number', models.PositiveSmallIntegerField(default=1)),
                ('initiated_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('failure_reason', models.TextField(blank=True)),
                ('webhook_received_at', models.DateTimeField(blank=True, null=True)),
                ('is_reconciled', models.BooleanField(default=False)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='bookings.booking')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted_by', to=settings.AUTH_USER_MODEL)),
                ('last_updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_last_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-initiated_at'],
                'indexes': [models.Index(fields=['booking', 'status'], name='payments_pa_booking_57d6de_idx')],
            },
        ),
    ]
