# Generated by Django 6.0.5 on 2026-07-14 10:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_booking_bookings_bo_listing_654f8c_idx'),
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='booking_group_id',
            field=models.UUIDField(blank=True, db_index=True, help_text='The booking_group_id of the associated booking, for easier querying across multiple payments.', null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='bookings.booking'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['booking_group_id', 'status'], name='payments_pa_booking_3eef38_idx'),
        ),
    ]
