# Generated by Django 6.0.5 on 2026-07-14 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_payment_booking_group_id_alter_payment_booking_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='booking_group_id',
            field=models.UUIDField(db_index=True, default='132491a8-dbed-48bb-8dea-92ccd251719f', help_text='The booking_group_id of the associated booking, for easier querying across multiple payments.'),
            preserve_default=False,
        ),
    ]
