# Generated by Django 6.0.2 on 2026-05-18 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_city_created_by_city_deleted_by_city_last_updated_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='country',
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='state',
            name='name',
            field=models.CharField(max_length=40),
        ),
    ]
