# Generated by Django 6.0.2 on 2026-05-24 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicletype',
            name='primary_image',
            field=models.ImageField(blank=True, null=True, upload_to='vehicle_type/images/'),
        ),
    ]
