# Generated by Django 6.0.2 on 2026-05-24 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_vehicletype_primary_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiclelisting',
            name='partial_payment_enabled',
        ),
        migrations.RemoveField(
            model_name='vehiclelisting',
            name='partial_payment_percentage',
        ),
        migrations.RemoveField(
            model_name='vehiclelisting',
            name='pay_at_pickup_enabled',
        ),
        migrations.AddField(
            model_name='pricingpackage',
            name='partial_payment_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='% of total to collect upfront when partial payment selected', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='pricingpackage',
            name='pay_at_pickup_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
