# Generated by Django 6.0.5 on 2026-05-27 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0004_listingblockedperiod_listingoperatingschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicletype',
            name='vehicle_type',
            field=models.CharField(blank=True, choices=[('CAR', 'Car'), ('BIKE', 'Bike'), ('SCOOTER', 'Scooter'), ('AUTO', 'Auto Rickshaw'), ('BUS', 'Bus'), ('VAN', 'Van')], db_index=True, max_length=50, null=True),
        ),
    ]
