# Generated by Django 6.0.5 on 2026-05-27 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0005_vehicletype_vehicle_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicletype',
            name='vehicle_type',
            field=models.CharField(choices=[('CAR', 'Car'), ('BIKE', 'Bike'), ('SCOOTER', 'Scooter'), ('AUTO', 'Auto Rickshaw'), ('BUS', 'Bus'), ('VAN', 'Van')], db_index=True, max_length=50),
        ),
    ]
