# Generated by Django 6.0.5 on 2026-06-12 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
        ('vehicles', '0008_vehiclereview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclereview',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='bookings.booking'),
        ),
    ]
