# Generated by Django 6.0.5 on 2026-06-16 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0009_alter_vehiclereview_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingpackage',
            name='km_limit',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
    ]
