# Generated by Django 6.0.5 on 2026-08-02 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0011_listingblockedperiod_count_operatingscheduletemplate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingblockedperiod',
            name='end_datetime',
            field=models.DateTimeField(blank=True, help_text='Leave blank for an open-ended/indefinite block.', null=True),
        ),
    ]
