# Generated by Django 6.0.5 on 2026-08-03 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0014_alter_vehicletype_options_remove_vehicletype_brand_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehicletype',
            options={'ordering': ['brand', 'name']},
        ),
        migrations.AddField(
            model_name='vehicletype',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vehicle_types', to='vehicles.brand'),
        ),
    ]
