# Generated by Django 6.0.5 on 2026-08-03 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0015_alter_vehicletype_options_vehicletype_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicletype',
            name='brand',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='vehicle_types', to='vehicles.brand'),
            preserve_default=False,
        ),
    ]
