# Generated by Django 6.0.5 on 2026-08-27 07:22

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0009_alter_booking_status'),
        ('vehicles', '0016_alter_vehicletype_brand'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiclereview',
            name='rating',
        ),
        migrations.AlterField(
            model_name='vehiclereview',
            name='booking',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='bookings.booking'),
        ),
        migrations.AlterField(
            model_name='vehiclereview',
            name='review_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.CreateModel(
            name='ReviewRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('criterion', models.CharField(choices=[('VEHICLE_CONDITION', 'Vehicle & Mechanical Condition'), ('CLEANLINESS', 'Cleanliness & Hygiene'), ('VENDOR_BEHAVIOR', 'Vendor Communication & Behavior'), ('HANDOVER_PROCESS', 'Pickup & Return Experience'), ('VALUE_FOR_MONEY', 'Value for Money')], max_length=32)),
                ('score', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted_by', to=settings.AUTH_USER_MODEL)),
                ('last_updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_last_updated_by', to=settings.AUTH_USER_MODEL)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='vehicles.vehiclereview')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('review', 'criterion'), name='unique_criterion_per_review')],
            },
        ),
    ]
