# Generated by Django 6.0.5 on 2026-06-02 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_phone_country_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_country_code',
            field=models.CharField(max_length=5),
        ),
    ]
