# Generated by Django 6.0.5 on 2026-06-23 15:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrations', '0001_initial'),
        ('locations', '0003_remove_city_country_alter_city_name_alter_state_name'),
        ('vehicles', '0011_listingblockedperiod_count_operatingscheduletemplate_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(help_text='Short benefit description shown on the card.')),
                ('icon_type', models.CharField(choices=[('STAR', 'Star'), ('CALCULATOR', 'Calculator'), ('LIGHTNING', 'Lightning Bolt'), ('BELL', 'Bell'), ('COIN', 'Coin / Rupee')], default='STAR', help_text='SVG icon rendered on the frontend. STAR is used for the featured yellow card.', max_length=20)),
                ('coupon_code', models.CharField(blank=True, help_text='Optional coupon code the customer enters at checkout.', max_length=50)),
                ('discount_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Flat discount in ₹.', max_digits=10, null=True)),
                ('min_order_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum booking value to unlock this offer.', max_digits=10, null=True)),
                ('valid_from', models.DateTimeField(blank=True, null=True)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('sort_order', models.PositiveSmallIntegerField(db_index=True, default=0, help_text='Lowest sort_order = featured (yellow) card.')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted_by', to=settings.AUTH_USER_MODEL)),
                ('last_updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_last_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['sort_order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='PopularRental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('display_name', models.CharField(blank=True, help_text='Override for the card title. Falls back to VehicleType.name.', max_length=200)),
                ('display_price', models.DecimalField(blank=True, decimal_places=2, help_text="'Starting from' price shown on the card. Falls back to VehicleType's cheapest live package.", max_digits=10, null=True)),
                ('display_image', models.ImageField(blank=True, help_text='Card image override. Falls back to VehicleType.primary_image.', null=True, upload_to='popular_rentals/')),
                ('tag', models.CharField(blank=True, help_text="Badge text shown on the card e.g. 'Best Seller', 'New'.", max_length=50)),
                ('sort_order', models.PositiveSmallIntegerField(db_index=True, default=0)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='popular_rentals', to='locations.city')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted_by', to=settings.AUTH_USER_MODEL)),
                ('last_updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_last_updated_by', to=settings.AUTH_USER_MODEL)),
                ('vehicle_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='popular_rentals', to='vehicles.vehicletype')),
            ],
            options={
                'ordering': ['city', 'sort_order', 'created_at'],
                'unique_together': {('city', 'vehicle_type')},
            },
        ),
    ]
