# Generated by Django 6.0.5 on 2026-06-28 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrations', '0002_offer_popularrental'),
        ('locations', '0003_remove_city_country_alter_city_name_alter_state_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='popularrental',
            name='pickup_location',
            field=models.ForeignKey(blank=True, help_text="Optional. Pin a specific pickup location for this card. Falls back to the vendor's primary location if left blank.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='popular_rentals', to='locations.pickuplocation'),
        ),
    ]
