# Generated by Django 6.0.5 on 2026-07-02 07:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrations', '0003_popularrental_pickup_location'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnouncementBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.TextField(help_text='Rich HTML content. Use the editor to add bold, links, etc. Font size is controlled by the frontend.')),
                ('page', models.CharField(choices=[('search_result', 'Search Result Page'), ('vehicle_detail', 'Vehicle Detail Page'), ('home', 'Home Page')], db_index=True, help_text='Which page this banner appears on.', max_length=50)),
                ('is_current', models.BooleanField(db_index=True, default=False, help_text='Only one banner per page can be current at a time.')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted_by', to=settings.AUTH_USER_MODEL)),
                ('last_updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_last_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True), ('is_current', True)), fields=('page',), name='unique_current_active_banner_per_page')],
            },
        ),
    ]
