# Generated by Django 6.0.5 on 2026-07-03 11:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrations', '0004_announcementbanner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cancellationtier',
            options={'ordering': ['payment_mode', '-min_hours_before_pickup']},
        ),
        migrations.AddField(
            model_name='cancellationtier',
            name='payment_mode',
            field=models.CharField(choices=[('FULL', 'Full Payment'), ('PARTIAL', 'Partial Payment')], db_index=True, default='FULL', help_text="Which payment mode's refund schedule this tier belongs to.", max_length=10),
        ),
        migrations.AlterField(
            model_name='cancellationtier',
            name='description',
            field=models.CharField(blank=True, help_text='Auto-generated if left blank.', max_length=300),
        ),
        migrations.AlterField(
            model_name='cancellationtier',
            name='label',
            field=models.CharField(blank=True, help_text='Auto-generated if left blank.', max_length=150),
        ),
        migrations.AddConstraint(
            model_name='cancellationtier',
            constraint=models.UniqueConstraint(fields=('policy', 'payment_mode', 'min_hours_before_pickup'), name='unique_tier_start_per_policy_mode'),
        ),
    ]
