# Generated by Django 6.0.5 on 2026-07-14 10:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrations', '0007_platformconfig'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('context', models.CharField(choices=[('VENDOR_RENTAL', 'Vendor Rental Service'), ('PLATFORM_COMMISSION', 'Platform Commission Service')], db_index=True, max_length=25)),
                ('name', models.CharField(max_length=100)),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cgst_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('sgst_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('igst_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('hsn_sac_code', models.CharField(blank=True, help_text='HSN/SAC code for invoicing, e.g. 9973 (rental services) or 9985 (support services). Confirm the correct code with your CA.', max_length=20)),
                ('is_current', models.BooleanField(db_index=True, default=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted_by', to=settings.AUTH_USER_MODEL)),
                ('last_updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_last_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-version'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('context',), name='unique_current_tax_rate_per_context')],
            },
        ),
    ]
