"""
Django settings for tripzido project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import environ

env = environ.Env()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

environ.Env.read_env(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-*t$q%a+b-getr)v_55n0hnn+*s$q*6jc5v$-gjuzi(aenhea@k"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]

CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://140.238.243.5",
    "http://192.168.1.4:3000",
    "http://192.168.1.2:3000",
    "https://tripzido-next.vercel.app",
]

CORS_ALLOW_CREDENTIALS = True

CSRF_TRUSTED_ORIGINS = [
    "https://tripzido-django.onrender.com",
    "http://140.238.243.5:3000",
    "http://localhost:3000",
    "https://tripzido-next.vercel.app",
]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "drf_spectacular",
    "rest_framework_simplejwt.token_blacklist",
    "django_filters",
    "corsheaders",
    "django_celery_results",
    "apps.core",
    "apps.bookings",
    "apps.locations",
    "apps.payments",
    "apps.reports",
    "apps.users",
    "apps.vendors",
    "apps.vehicles",
    "apps.administrations",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"

AUTH_USER_MODEL = "users.User"

# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": env("DATABASE_NAME"),
        "USER": env("DATABASE_USER"),
        "PASSWORD": env("DATABASE_PASSWORD"),
        "HOST": env("DATABASE_HOST", default="localhost"),
        "PORT": env("DATABASE_PORT", default="5432"),
    }
}

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": env("CACHING_REDIS_URL"),
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        },
    }
}

CELERY_BROKER_URL = env("CELERY_BROKER_URL")  # same Redis you already use for caching
# CELERY_RESULT_BACKEND = "redis://127.0.0.1:6379/1"
CELERY_RESULT_BACKEND = "django-db"  # store results in Django DB (POSTGRESQL)
CELERY_TASK_ACKS_LATE = True  # if a worker crashes, the task will be re-queued
CELERY_TASK_RESULT_EXPIRES = 604800  # clean up after 7 days
CELERY_BROKER_TRANSPORT_OPTIONS = {
    "visibility_timeout": 3600  # 3600 seconds = 1 hour
}  # if a worker crashes while processing a task, the task will be re-queued after 1 hour (default is 24 hours)


FAST2SMS_API_KEY = env("FAST2SMS_API_KEY")
TURNSTILE_SECRET_KEY = env("TURNSTILE_SECRET_KEY")  #


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


REST_FRAMEWORK = {
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",  # ← change this too
    ],
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework_simplejwt.authentication.JWTAuthentication",  # ← add
    ],
    "DEFAULT_FILTER_BACKENDS": [
        "django_filters.rest_framework.DjangoFilterBackend",  # filtering
        "rest_framework.filters.SearchFilter",  # searching
        "rest_framework.filters.OrderingFilter",  # ordering
    ],
    "DEFAULT_PAGINATION_CLASS": "apps.core.pagination.CustomPagination",
    "PAGE_SIZE": 10,
}

from datetime import timedelta

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=300),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": True,  # new refresh token on every refresh
    "BLACKLIST_AFTER_ROTATION": True,  # old refresh token becomes invalid
    "AUTH_HEADER_TYPES": ("Bearer",),  # Authorization: Bearer <token>
}

SPECTACULAR_SETTINGS = {
    "TITLE": "Tripzido API",
    "DESCRIPTION": "API documentation for Tripzido",
    "VERSION": "1.0.0",
    "SECURITY": [{"BearerAuth": []}],  # ← add
    "COMPONENTS": {  # ← add
        "securitySchemes": {
            "BearerAuth": {
                "type": "http",
                "scheme": "bearer",
                "bearerFormat": "JWT",
            }
        }
    },
    "SWAGGER_UI_SETTINGS": {
        "persistAuthorization": True,  # token survives refresh ← your previous issue
        "displayRequestDuration": True,  # shows how long each request took
        "filter": True,  # adds a search/filter bar for endpoints
        "deepLinking": True,  # URL updates when you open an endpoint
    },
}


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"


MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"
