# Generated by Django 6.0.5 on 2026-07-09 11:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0011_listingblockedperiod_count_operatingscheduletemplate_and_more'),
        ('vendors', '0003_alter_vendorterms_created_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='vendorsubscription',
            index=models.Index(fields=['vendor', 'is_current', 'status'], name='vendors_ven_vendor__0320b2_idx'),
        ),
        migrations.AddIndex(
            model_name='vendorterms',
            index=models.Index(fields=['listing', 'is_current'], name='vendors_ven_listing_5a6f05_idx'),
        ),
    ]
