# Generated by Django 6.0.5 on 2026-07-10 10:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0004_vendorsubscription_vendors_ven_vendor__0320b2_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='vendorterms',
            name='vendors_ven_listing_5a6f05_idx',
        ),
        migrations.AddField(
            model_name='vendorterms',
            name='vendor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='vendor_terms', to='vendors.vendor'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='vendorterms',
            index=models.Index(fields=['vendor', 'is_current'], name='vendors_ven_vendor__7aa99c_idx'),
        ),
        migrations.RemoveField(
            model_name='vendorterms',
            name='listing',
        ),
    ]
