# Generated by Django 6.0.5 on 2026-10-10 10:01

import os
import shutil

import apps.core.storage
import apps.vendors.models
from django.conf import settings
from django.db import migrations, models

DOCS_SUBDIR = os.path.join("vendor", "documents")


def _move_all(src_root, dst_root):
    """
    Moves every file under <src_root>/vendor/documents/ to the same
    relative path under <dst_root>. DB rows store paths relative to the
    storage root ("vendor/documents/x.pdf"), so they stay valid without
    any row updates. Never overwrites: a name clash is left in place
    and reported, so nothing is lost.
    """
    src_dir = os.path.join(src_root, DOCS_SUBDIR)
    dst_dir = os.path.join(dst_root, DOCS_SUBDIR)
    if not os.path.isdir(src_dir):
        return
    os.makedirs(dst_dir, exist_ok=True)
    moved, skipped = 0, []
    for name in os.listdir(src_dir):
        src = os.path.join(src_dir, name)
        dst = os.path.join(dst_dir, name)
        if not os.path.isfile(src):
            continue
        if os.path.exists(dst):
            skipped.append(name)
            continue
        shutil.move(src, dst)
        moved += 1
    print(f"\n  Moved {moved} vendor document file(s) {src_dir} -> {dst_dir}")
    if skipped:
        print(f"  Skipped (already exist at destination): {', '.join(skipped)}")


def move_to_private(apps, schema_editor):
    _move_all(str(settings.MEDIA_ROOT), str(settings.PRIVATE_MEDIA_ROOT))


def move_to_public(apps, schema_editor):
    _move_all(str(settings.PRIVATE_MEDIA_ROOT), str(settings.MEDIA_ROOT))


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0006_vendorteammember'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendordocument',
            name='file',
            field=models.FileField(storage=apps.core.storage.private_storage, upload_to=apps.vendors.models.vendor_document_upload_to),
        ),
        migrations.RunPython(move_to_private, move_to_public),
    ]
