# Generated by Django 6.0.5 on 2026-06-20 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='payment',
            name='bookings_pa_booking_bf00c8_idx',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
