# Generated by Django 6.0.5 on 2026-06-21 15:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_remove_payment_bookings_pa_booking_bf00c8_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingCancellation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('cancelled_by_role', models.CharField(choices=[('CUSTOMER', 'Customer'), ('VENDOR', 'Vendor'), ('ADMIN', 'Admin'), ('SYSTEM', 'System (Auto)')], max_length=20)),
                ('reason_code', models.CharField(choices=[('CHANGE_OF_PLANS', 'Change of Plans'), ('FOUND_BETTER', 'Found a Better Option'), ('BOOKED_BY_MISTAKE', 'Booked by Mistake'), ('TRIP_CANCELLED', 'Trip Cancelled'), ('VENDOR_BREAKDOWN', 'Vehicle Breakdown'), ('VENDOR_EMERGENCY', 'Vendor Emergency'), ('ADMIN_ACTION', 'Admin Action'), ('OTHER', 'Other')], max_length=30)),
                ('reason_text', models.TextField(blank=True)),
                ('policy_version', models.PositiveIntegerField(blank=True, null=True)),
                ('hours_before_pickup_at_cancellation', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('refund_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('refundable_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('forfeited_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cancellation', to='bookings.booking')),
                ('cancelled_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cancellations_initiated', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted_by', to=settings.AUTH_USER_MODEL)),
                ('last_updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_last_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
