# Generated by Django 6.0.5 on 2026-07-07 06:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrations', '0006_legaldocument_customertcacceptance_and_more'),
        ('bookings', '0003_bookingcancellation'),
        ('vendors', '0003_alter_vendorterms_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='platform_tc_version',
        ),
        migrations.AddField(
            model_name='booking',
            name='platform_tc_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bookings_accepted', to='administrations.legaldocument'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='vendor_terms_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bookings_accepted', to='vendors.vendorterms'),
        ),
    ]
