# Generated by Django 6.0.5 on 2026-07-07 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_remove_booking_platform_tc_version_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='platform_tc_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='booking',
            name='vendor_terms_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
