# Generated by Django 6.0.5 on 2026-07-09 11:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrations', '0007_platformconfig'),
        ('bookings', '0005_booking_platform_tc_snapshot_and_more'),
        ('locations', '0003_remove_city_country_alter_city_name_alter_state_name'),
        ('vehicles', '0011_listingblockedperiod_count_operatingscheduletemplate_and_more'),
        ('vendors', '0003_alter_vendorterms_created_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['listing', 'dropoff_date', 'pickup_date'], name='bookings_bo_listing_654f8c_idx'),
        ),
    ]
