# Generated by Django 6.0.5 on 2026-07-14 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrations', '0008_taxrate'),
        ('bookings', '0006_booking_bookings_bo_listing_654f8c_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='commission_tax_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='booking',
            name='commission_tax_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='booking',
            name='commission_tax_rate',
            field=models.ForeignKey(blank=True, limit_choices_to={'context': 'PLATFORM_COMMISSION'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bookings_as_commission_tax', to='administrations.taxrate'),
        ),
        migrations.AddField(
            model_name='booking',
            name='tax_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='booking',
            name='vendor_tax_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='booking',
            name='vendor_tax_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='booking',
            name='vendor_tax_rate',
            field=models.ForeignKey(blank=True, limit_choices_to={'context': 'VENDOR_RENTAL'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bookings_as_vendor_tax', to='administrations.taxrate'),
        ),
    ]
