# Generated by Django 6.0.5 on 2026-07-27 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_booking_commission_tax_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_offline',
            field=models.BooleanField(db_index=True, default=False, help_text="True if this booking was created offline by the vendor (e.g. a walk-in customer), rather than through the platform's own online checkout flow."),
        ),
    ]
