# Generated by Django 6.0.5 on 2026-08-27 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0009_alter_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='verification_pin',
            field=models.CharField(blank=True, default='', help_text='Random 4-digit PIN generated at booking time. Shown to the customer while the booking is CONFIRMED; the vendor must enter it correctly before the trip can be marked ONGOING.', max_length=4),
        ),
    ]
