# Generated by Django 6.0.5 on 2026-09-03 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='portal',
            field=models.CharField(choices=[('VENDOR', 'Vendor Portal'), ('ADMIN', 'Admin Portal'), ('CUSTOMER', 'Customer Portal')], db_index=True, default='ADMIN', max_length=20),
            preserve_default=False,
        ),
    ]
