# Generated by Django 6.0.5 on 2026-09-03 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('NEW_BOOKING', 'New Booking'), ('LISTING_SUBMITTED', 'Listing Submitted for Review'), ('LISTING_APPROVED', 'Listing Approved'), ('LISTING_REJECTED', 'Listing Rejected'), ('LISTING_SUSPENDED', 'Listing Suspended'), ('BOOKING_CANCELLED', 'Booking Cancelled'), ('PAYOUT_PAID', 'Payout Paid'), ('PAYOUT_FAILED', 'Payout Failed')], db_index=True, max_length=30),
        ),
    ]
